GET http://localhost:3001/api/persons/

###
GET http://localhost:3001/api/info

###
GET http://localhost:3001/api/persons/639fe4c731aefb8cdbe8629c

###
PUT http://localhost:3001/api/persons/639fe4c731aefb8cdbe8629c
Content-Type: application/json

{
  "name": "miles",
  "number": "225-123-1234"
}

###
DELETE http://localhost:3001/api/persons/63a11949bdda063f983aaa04

###
POST http://localhost:3001/api/persons
Content-Type: application/json

# { 
#     "name": "Mary Poppendieck", 
#     "number": "39-23-6423122"
# }

{
  "name": "Jared Tim",
  "number": "84-48-209790855"
}